@echo off
SET BASE=%~dp0BASE
SET THEIRS=%~dp0THEIRS
SET YOURS=%~dp0YOURS
SET OUTPUT=%~dp0OUTPUT
SET CHANGE=%~dp0CHANGE
SET CHANGEBASE=%~dp0CHANGEBASE
SET BC3=C:\Program Files\Beyond Compare 3\bcomp.com
